nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: ["http://localhost:5173"]
    allow_headers: ["Content-Type", "Authorization", "Accept", "Origin"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    expose_headers: ["Link"]
    max_age: 3600

  paths:
    "^/api/":
      allow_origin: ["http://localhost:5173"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allow_headers: ["Content-Type", "Authorization", "Accept", "Origin"]
      max_age: 3600
